### ISSUE TITLE
Scale up images?

### ISSUE THREAD

**Issue by kennethormandy** [kennethormandy/figment#2]
Images that are too small should scale within `breakout`s, possibly within all `figure--something`-s.

![screen shot 2014-10-14 at 1 10 15](https://cloud.githubusercontent.com/assets/1581276/4635922/30e67fec-53de-11e4-8302-bcb36712f147.png)

**Comment by kennethormandy** [comment]
The real question for this is should relevant normalizing browser styles be brought in? I am leaning towards yes:

```css
figure {
  margin: 0;
}

figure img {
  width: 100%;
}
```
